---
- hosts: hosts
  vars_files:
    - vars.yml

  pre_tasks:
  - name: Copy project to the remote host
    synchronize:
      src: "{{ playbook_dir }}"
      dest: "{{ dotfile_location }}"

  roles:
    - { role: geerlingguy.security, become: true }
    - { role: robertdebock.rpmfusion, become: true }
    - role: gantsign.antigen
      become: true
      vars:
        users:
          - username: vid
            antigen_libraries:
              - name: oh-my-zsh
            antigen_theme:
              name: robbyrussell
            antigen_bundles:
              - name: git
              - name: docker
              - name: sudo
              - name: command-not-found
              - name: ssh-agent
              - name: zsh-completions
                url: zsh-users/zsh-completions
              - name: zsh-autosuggestions
                url: zsh-users/zsh-autosuggestions
              - name: zsh-syntax-highlighting
                url: zsh-users/zsh-syntax-highlighting
    - role: git
    - role: kitty
    - role: rclone
    - role: aws
    - role: kde
    - role: taskwarrior

  tasks:
  - name: Install essential packages
    package:
      name: "{{ essential_packages }}"
      state: latest
      update_cache: true
    become: True

  - name: Install additional packages
    package:
      name: "{{ additional_packages }}"
      state: latest
      update_cache: true
    become: True
    when: install_additional_packages is defined and install_additional_packages

  - name: Remove unwanted packages
    package:
      name: "{{ remove_packages }}"
      state: absent
    become: True

- import_playbook: vscode.yml