---
- name: Install kitty
  package:
    name: kitty
    state: latest
  become: True

- name: Create kitty config directory
  file:
    path: ~/.config/kitty
    state: directory

- name: Symlink kitty.conf
  file:
    src: ~/dotfiles/roles/kitty/files/kitty.conf
    dest: ~/.config/kitty/kitty.conf
    state: link
