---
- name: Install git
  package:
    name: git
    state: latest
  become: True

- name: Symlink .gitconfig
  file:
    src: ~/dotfiles/roles/git/files/.gitconfig
    dest: ~/.gitconfig
    state: link
